name: src
description: 'Smart lamp Flutter app for IoT labs.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  http: ^1.2.2
  mqtt_client: ^10.5.1
  provider: ^6.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
